#! /bin/sh

sxhkd &

#--AutoStart--#
#~/.config/scripts/cleanfullscreen &
xrdb ~/.Xresources &
killall "picom"
picom --experimental-backend &
killall polybar
feh --bg-scale --no-fehbg ~/Pictures/Backgrounds/forest.png &
killall "dunst"
dunst &
$HOME/.config/polybar/launch.sh


#--Monitors--#
bspc monitor DP-2 -d 1 2 3 4 5 6 7 
bspc monitor HDMI-0 -d I II III 

#--Globals--#
bspc config automatic_scheme alternate
bspc config initial_polarity second_child
bspc config pointer_modifier shift
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config click_to_focus none

bspc config pointer_follows_focus false
bspc config focus_follows_pointer true
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

# borders
#bspc config normal_border_color "#4c566a"
#bspc config active_border_color "#1e1e1e"
#bspc config focused_border_color "#453175"
#bspc config presel_feedback_color "#5e81ac"
#bspc config urgent_border_color "#dd2727"

bspc config normal_border_color "#453175"
bspc config active_border_color "#1e1e1e"
bspc config focused_border_color "#b03356"  #"#ab153f"
#bspc config presel_feedback_color "#5e81ac"

#--Monitor and Desktop Settings--#
bspc config -m DP-2 border_width    2
bspc config window_gap              12

# Mon 1
bspc config top_padding 35 
bspc config bottom_padding 15 
bspc config left_padding  5
bspc config right_padding 5

# Mon 2
bspc config -m HDMI-0 top_padding -13
bspc config -m HDMI-0 bottom_padding -13
bspc config -m HDMI-0 left_padding -13
bspc config -m HDMI-0 right_padding -12


bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true



bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a osmo state=floating
